Done
maybe-hello-world/hometask_43506_3 pull request #2
Opened 2018-10-07 16:20 UTC by tFNiYaFF

Для теста парсера: python parser_test.py <имя_файла_лога> <номер_события>
Для теста сортировки: python sort_test.py <массив чисел через запятую>

2018-10-07 19:46 UTC, maybe-hello-world requested changes
В парсере dhcp: ок.
В сортировке: отсутствует документирование кода, отсутствует проверка на входные типы

2018-10-08 10:44 UTC, maybe-hello-world approved these changes
Non blocking problems highlighted

2018-10-08 10:44 UTC, maybe-hello-world commented on sort.py
> +    """Приватная функция. Используйте функцию quick_sort вместо неё."""
В языке Python есть специальные соглашения по именованию, регулирующие названия приватных объектов. Для указания того, что функция является внутренней и не предназначена для использования снаружи обычно данные функции именуются с одного или двух знаков подчеркивания (_ или __)

2018-10-08 10:44 UTC, maybe-hello-world commented on sort.py
> +    """Приватная функция сортировки, используемая в алгоритме. Не для внешнего использования! Для сортировки используйте
Аналогично комментарию выше

2018-10-08 10:44 UTC, maybe-hello-world commented on sort_test.py
> +        print(repr(e))
Вместо repr (если уж вы взялись его использовать) лучше здесь использовать str(e).
Задача repr - вывести текстовое описание объекта, позволяющее его (в идеале) однозначно восстановить, например repr(date.today()) выведет "datetime.date(2018, 10, 8)".
Str же служит для выведения человекочитаемого значения, str(date.today()): "2018-10-08".
Вам нужно вывести текст для человека или иметь возможность воссоздать инстанс исключения? =)

2018-10-08 10:45 UTC, maybe-hello-world commented
Done

2018-10-08 10:45 UTC, merged

2018-10-08 10:56 UTC, tFNiYaFF commented on sort_test.py
> +        print(repr(e))
@maybe-hello-world 
Ну да, надо для человека). 
Сначала сделал str(e), но, потом, вычитав про то, что str в случае, когда кодировка поломается, кинет exception, решил использовать repr. Или это не очень хорошая практика и все же всегда надо str использовать?

2018-10-08 11:02 UTC, maybe-hello-world commented on sort_test.py
> +        print(repr(e))
Не знаю, какого года статью вы читали, но этот баг был в версиях 2.6 и в 3й даже не упоминается . =)
https://bugs.python.org/issue2517