Merge sort and logs parser
maybe-hello-world/hometask_43506_3 pull request #6
Opened 2018-10-14 22:31 UTC by TiMoon54

Done:

- Merge sort it-self
- Some sort tests
- dhcp server logs parser
- parsing results (dump json file)

ok?

2018-10-15 09:14 UTC, maybe-hello-world requested changes
Ну уж совесть то иметь надо, сдавать мне два одинаковых кода сортировки в одно и то же время. 
Те же замечания, что и у @startpointforl
(и, кстати, у нее реализовано эффективнее)

2018-10-15 09:16 UTC, TiMoon54 commented
Алгоритм один и тот же, ладно бы задание на выбор давалось и мы внезапно сделали одинаковое.

2018-10-15 09:19 UTC, maybe-hello-world commented
Читайте внимательнее замечания, там нету blocking requests, связанных с повторяемостью кода.

2018-10-15 09:26 UTC, moyous commented
Так даже если бы были, какое-то неуважение с "совесть то иметь надо".

2018-10-15 10:08 UTC, maybe-hello-world commented
Прекрасно, далее буду относиться к Вам с максимальным уважением ^^
Следующие замечания являются блокирующими:

1. Низкая эффективность алгоритма, библиотека NumPy и ее возможности не используются вообще. А на досуге рекомендую почитать про реализацию списков в питоне и почему операция lst.pop(0) требует O(n) времени.
2. Отсутствует проверка входных типов данных. Breaking example: [1, 2, 3, None]
3. Полностью отсутствует документирование кода.

Жду Ваших изменений.

2018-10-16 07:03 UTC, maybe-hello-world requested changes
Все еще не решена проблема производительности и проверки входных значений.
Я абсолютно не против, чтобы это было реализовано эффективнее, чем проверка на тип каждого из элементов. Но если реализовываете - делайте это качественно.

2018-10-16 07:03 UTC, maybe-hello-world commented on mergeSort.py
> +def sort(m):
Названия приватных функций внутри модуля лучше именовать с leading underscore, тогда они не будут импортироваться при "from mergeSort import *"
Подробнее: https://tproger.ru/translations/5-ways-of-using-underscore-in-python/#
Неблокирующий комментарий.

2018-10-16 07:03 UTC, maybe-hello-world commented on mergeSort.py
> +def merge(left, right):
см. выше, аналогично

2018-10-16 07:03 UTC, maybe-hello-world commented on mergeSort.py
> +                    raise ValueError('List should not contain any None values. Only int or float is allowed.')
Все еще не выполняет заданных функций.
Breaking example: [1, 2, 3, numpy.nan]
Блокирующий комментарий.
P.S. Рекомендую таки реализовать нормальную проверку, а то все возможные типы не перечислите же.

2018-10-16 14:12 UTC, maybe-hello-world requested changes
Все еще ужасная эффективность решения. 
Смотрите комментарии про счетчики и numpy, остальные - для информации.

2018-10-16 14:12 UTC, maybe-hello-world commented on dhcpParser.py
> +        file.close()
К сожалению, на паре было достаточно мало времени, чтобы обсудить аспекты языка, которые были не поняты, но т.к. мне вопросов не задавали, я решил, что всем все было понятно.
Менеджеры контекста были созданы для того, чтобы вы не закрывали принудительно файл. После объявления открытия файла в with ... as ..., когда вы вернетесь к предыдущему блоку (на один отступ назад), файл будет автоматически закрыт.
Подробнее: https://pythonworld.ru/osnovy/with-as-menedzhery-konteksta.html

2018-10-16 14:12 UTC, maybe-hello-world commented on mergeSort.py
> +            if not (type(val) == int or type(val) == float):
Ну вот, а ведь вы почти дошли до оптимального решения - приводить к массиву и проверять на наличие np.nan конечный массив...
Кроме нанов там могут оказаться только бесконечности, но сортировка с ними прекрасно работает.
Ну ладно.

2018-10-16 14:12 UTC, maybe-hello-world commented on mergeSort.py
> +    left.reverse()
1. Есть более эффективный способ делать весь этот алгоритм, а не "разворот - поп - разворот". Почему не завести счетчики для каждого из массивов и инкрементировать их, идя по ним, а потом конечный массив просто удалять?
2. Все еще не используется NumPy. Возьмите свой способ, отсортируйте массив из нескольких миллионов элементов, а потом реализуйте на NumPy и посмотрите на разницу.

2018-10-16 14:12 UTC, maybe-hello-world commented on dhcpParser.py
> +        file.close()
Неблокирующий.

2018-10-16 14:12 UTC, maybe-hello-world commented on mergeSort.py
> +            if not (type(val) == int or type(val) == float):
Неблокирующий.

2018-10-16 14:12 UTC, maybe-hello-world commented on mergeSort.py
> +    left.reverse()
Блокирующий.

2018-10-16 22:03 UTC, maybe-hello-world approved these changes
К сожалению, эффективность вашего кода не просто оставляет желать лучшего, она ужасна.
Для примера я взял три реализации одного и того же алгоритма - вашу и двух ваших одногруппников. Увы, но ваша реализация в три раза хуже даже человека, сдававшего работу вместе с вами, уже не говоря о других (далеко не идеальных) реализациях.
Просто "использовать NumPy" не делает код оптимизированным, и вместо того, чтобы выделить изначально массив размером left + right и смещаться по нему, записывая результат, вы предпочитаете делать тяжелые операции удаления и аппенда массивов.
В таблице также указано время TiMoon54 Fixed - это ваша реализация, в которой я изменил строчки с 47 по 61 и переписал на цикл с счетчиками. Это заняло у меня 30 минут, включая дебаг. И одно это дало улучшение производительности в 9 раз, а ведь это наивная реализация сортировки, даже без оптимизаций.

В общем, в этот раз заапрувлено, но лишь из жалости.


TiMoon54 Sorted: True
ANAKOT Sorted: True
MAKPETR Sorted: True
TiMoon54 Fixed Sorted: True

Timeit TiMoon54: 0.9247300291
Timeit ANAKOT: 0.33903808259999996
Timeit MAKPETR: 0.06352345170000007
Timeit TiMoon54 Fixed: 0.11071929184999992

2018-10-16 22:03 UTC, maybe-hello-world commented on mergeSort.py
> +            right = np.delete(right, -1)
К сожалению, сложность этой операции также O(n).

2018-10-16 22:06 UTC, merged

2018-10-16 22:46 UTC, TiMoon54 commented
Согласен.

> Блюди́те у́бо, ка́ко опа́сно хо́дите, не я́коже нему́дри, но я́коже прему́дри, 
> иску́пу­ю­ще вре́мя, я́ко дні́е лука́ви су́ть. 

(Еф.5:15-16)

> Досажде́нiе му́жа смиря́етъ, а смире́н­ныя утвержда́етъ Госпо́дь въ сла́вѣ. 

(Прит.29:23)